---
language: ruby
sudo: false
cache: bundler
script:
  - bundle exec rake spec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.4.5
  - 2.5.3
env:
  - FACTER_GEM_VERSION="~> 1.6.0"
  - FACTER_GEM_VERSION="~> 1.7.0"
  - FACTER_GEM_VERSION="~> 2.0.0"
  - FACTER_GEM_VERSION="~> 2.1.0"
  - FACTER_GEM_VERSION="~> 2.2.0"
  - FACTER_GEM_VERSION="~> 2.3.0"
  - FACTER_GEM_VERSION="~> 2.4.0"
  - FACTER_GEM_VERSION="~> 2.0"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
notifications:
  email: false
